channels:
  - conda-forge
  - nodefaults
dependencies:
  - python >=3.11,<3.12
  - h5netcdf
  - matplotlib-base
  - mpld3
  - numpy >=1.23,<3
  - pandas >=2.2,<3
  - pyproj
  - pystac-client
  - rasterio
  - requests
  - rioxarray
  - scipy
  - streamlit >=1.42
  - xarray
  - xpystac >=0.4,<0.5
  - zarr
