channels:
  - conda-forge
  - nodefaults
dependencies:
  - python >=3.11,<3.12
  - bottleneck
  - dask
  - defusedxml
  - geopandas >=1.0.1
  - h5netcdf
  - h5py
  - matplotlib-base
  - mpld3
  - numpy >=1.23,<3
  - packaging
  - pandas >=2.2,<3
  - pyarrow
  - pyogrio
  - pyproj
  - pystac-client
  - pytables
  - python-dateutil
  - rasterio
  - requests
  - rioxarray
  - scikit-learn
  - scipy
  - shapely
  - streamlit >=1.42
  - tqdm
  - xarray
  - xpystac >=0.4,<0.5
  - zarr
